### ISSUE TITLE
Fix code scanning alert - The variable 'SAMLAudiences' is assigned but never used.

### ISSUE THREAD

**Issue by rebelinux** [AsBuiltReport/AsBuiltReport.VMware.UAG#6]
Tracking issue for:
- [ ] https://github.com/AsBuiltReport/AsBuiltReport.VMware.UAG/security/code-scanning/1

**Comment by childebrandt42** [comment]
Can not open the link, but fixed it on Get-AbrTLSServerCertificateSetting

**Comment by rebelinux** [comment]
Sorry, I will investigate why you can't see the link
